// T-20260607-foot-REDPAY-PORT — Reconciliation 매칭 엔진 (4-Tier) 풋센터 이식
//
// 출처: T-20260520-crm-PAY-RECON-001 M2 (롱레CRM 검증 완료). 풋 변형 적용.
// 순수 함수 모듈. Supabase / Deno 의존 없음 → vitest 단위 테스트 가능.
//
// ── 풋 변형 (롱레와 다른 점) ─────────────────────────────────────────────────
//   롱레는 단일 DB에 longlasting/vegas 다출처 payments 가 섞여 source_system 으로
//   분리했으나, 풋CRM payments 에는 source_system 컬럼이 없음(단일 도메인).
//   → Tier 1/2/3 의 source_system 필터 제거. card + payment + amount + 시간 윈도로 매칭.
//
// ── 개발 목적 본질 (대표 직접 지시 2026-05-26) ─────────────────────────────────
//   직원이 결제할 때 결제번호를 넣는 불편함을 줄이는 게 핵심.
//   결제 시간·시점·금액 정보 기반 자동 매칭.
//   승인번호·TID 입력은 보너스(있으면 우선, 없어도 매칭 시도).
//
// ── 4-Tier 매칭 우선순위 ──────────────────────────────────────────────────────
//   Tier 0  — Direct (보너스): external_approval_no / external_tid 직접 일치
//   Tier 1  — Tight (95% 목표): tid whitelist + card + amount + [+15min]
//   Tier 2  — Loose: 같은 조건 + [+30min], single candidate만 매칭
//   Tier 3  — Daily Unique: KST 같은 날짜 + amount unique
//   Tier 4  — Manual: 수동 매칭 큐 (multi_candidate or fallback)
//
// ── 시간 방향 (단방향 +방향) ─────────────────────────────────────────────────
//   redpay.approved_at  = 단말기 승인 시각 (먼저)
//   CRM.created_at      = 직원이 CRM에 입력한 시각 (나중)
//   윈도: [approved_at, approved_at + N분]
//
// ── 알림 카테고리 (AC-3) ─────────────────────────────────────────────────────
//   'missing_in_crm'    — 단말기 ○ CRM ✕ (매출 분실 위험)
//   'missing_at_van'    — CRM ○ 단말기 ✕
//   'amount_mismatch'   — 양쪽 있지만 금액 다름
//   'refund_not_in_crm' — 단말기 취소 CRM active

// ── 타입 ────────────────────────────────────────────────────────────────────

/** Redpay raw_transactions 레코드 (DB 칼럼과 1:1) */
export interface RawTransaction {
  id:              string;
  clinic_id:       string;
  external_trxid:  string;
  external_status: string;   // Y=승인 N=취소 M=부분취소 X=오류
  amount:          number;
  approval_no:     string | null;
  root_trxid:      string | null;
  tid:             string | null;
  approved_at:     string | null;  // ISO8601 UTC
  matched_payment_id: string | null;
  /** redpay 원본 JSON(merchant.id 포함) — center(멀티센터 스코핑) 파생용. T-20260714-foot-REDPAY-DOHSU-CLOSING-POLLER */
  raw_payload?:    Record<string, unknown> | null;
}

/** CRM payments 레코드 (reconciliation에 필요한 필드만)
 *
 * 주의: DB 실컬럼은 paid_at이 없고 created_at만 있음.
 * created_at = 직원이 결제를 CRM에 입력한 시각 (auto-generated by DB).
 * source_system: 풋CRM 에는 없음 → optional (매칭 로직 미사용).
 */
export interface CrmPayment {
  id:              string;
  clinic_id:       string;
  amount:          number;
  method:          string;   // 'card' | 'cash' | 'transfer' | 'membership'
  payment_type:    string;   // 'payment' | 'refund'
  source_system?:  string;   // 풋: 미사용 (호환 위해 optional 보존)
  created_at:      string | null;  // ISO8601 UTC — 직원 입력 시각
  external_trxid:  string | null;
  external_approval_no: string | null;
  external_tid:    string | null;
  reconciled_at:   string | null;  // null = 미매칭
}

/** 매칭 결과 단건 */
export interface MatchResult {
  raw_transaction_id: string;
  payment_id:         string | null;
  match_rule:
    | "tier0_direct"
    | "tier1_tight"
    | "tier2_loose"
    | "tier3_daily_unique"
    | "tier4_manual"
    | null;
  /** 자동 매칭 성공 여부 */
  matched:       boolean;
  /** 수동 매칭 큐로 이관 여부 */
  needs_manual:  boolean;
  /** 매칭 실패 사유 */
  fail_reason:   string | null;
}

/** reconciliation_log 이벤트 페이로드 (DB insert 직전) */
export interface ReconEvent {
  clinic_id:          string;
  raw_transaction_id: string | null;
  payment_id:         string | null;
  event_type:
    | "auto_matched"
    | "match_failed"
    | "missing_in_crm"
    | "missing_at_van"
    | "amount_mismatch"
    | "refund_not_in_crm";
  match_rule:
    | "tier0_direct"
    | "tier1_tight"
    | "tier2_loose"
    | "tier3_daily_unique"
    | "tier4_manual"
    | null;
  mismatch_reason: string | null;
  external_trxid:  string | null;
  external_amount: number | null;
  crm_amount:      number | null;
  /** 알림 페이로드 (실발송은 M3 이후 — M0에서는 로그만) */
  alert_payload:   AlertPayload | null;
  /**
   * 멀티센터 recon 스코핑(canonical brand 토큰). 'foot'=풋 / 'body'=도수(재활).
   * merchant band 로 명시 파생(default-mapping 금지). insertReconEvents 직전 index.ts 에서 stamp.
   * T-20260714-foot-REDPAY-DOHSU-CLOSING-POLLER / DA da_decision_body_redpay_center_column.
   */
  center?:         "foot" | "body";
}

/** Slack 알림 페이로드 (M3에서 실발송) */
export interface AlertPayload {
  alert_type:       ReconEvent["event_type"];
  target_channel:   string;
  external_trxid:   string | null;
  external_amount:  number | null;
  crm_amount:       number | null;
  approved_at:      string | null;
  mismatch_reason:  string | null;
}

// ── 상수 ────────────────────────────────────────────────────────────────────

/** Tier 1 단방향 윈도: [approved_at, +15분] */
export const TIER1_WINDOW_MS = 15 * 60 * 1000;

/** Tier 2 단방향 윈도: [approved_at, +30분] */
export const TIER2_WINDOW_MS = 30 * 60 * 1000;

/** 환불/취소 상태 목록 */
export const CANCELLED_STATUSES = new Set(["N", "X", "M"]);

// ── 관측행 판별 (T-20260723-foot-REDPAY-PLANB-OBSERVE-MODE) ──────────────────────
//   웹훅 관측모드(PAYMENT_AUTO_MODE=observe)가 적재한 행은 raw_payload._mode='observe'.
//   ★ 관측 전용 = 매칭/대사 대상에서 제외(실 payments 승격 금지). 폴러 원본행(_mode 부재)·
//   auto 웹훅행(_mode='auto')은 매칭 대상(false). DB 쿼리 제외 + 이 술어로 JS-측 2차 방어.
export function isObserveRow(
  raw: { raw_payload?: Record<string, unknown> | null } | null | undefined,
): boolean {
  const m = raw?.raw_payload?._mode;
  return typeof m === "string" && m.trim().toLowerCase() === "observe";
}

// ── 헬퍼 ─────────────────────────────────────────────────────────────────────

/**
 * ISO8601 UTC 문자열 → KST 날짜 문자열 (YYYY-MM-DD).
 * 타임존 오프셋 없이 단순 +9h 연산.
 */
export function toKstDateStr(isoUtc: string): string {
  const ms = new Date(isoUtc).getTime();
  const kstMs = ms + 9 * 60 * 60 * 1000;
  return new Date(kstMs).toISOString().slice(0, 10);
}

/**
 * CRM payment가 매칭 가능한 상태인지 확인.
 * reconciled_at IS NULL AND external_trxid IS NULL
 */
function isUnmatchedCrm(p: CrmPayment): boolean {
  return p.reconciled_at === null && p.external_trxid === null;
}

// ── Tier 0 — Direct 매칭 (3단 캐스케이드) ─────────────────────────────────────
//
// T-20260728-foot-REDPAY-RECONCILE-TIER0-TRXID-HARDENING
//   DA CONSULT-REPLY: GO (SSOT=da_decision_foot_redpay_reconcile_tier0_trxid_hardening_20260728.md)
//
//   ▸ 폐기 (안티패턴): 기존 findTier0Direct 는 bare approval_no OR bare tid 단일키를
//     그대로 auto-link 했다. 단일키 매칭은 대량 false-merge 위험이다 —
//       · approval_no 는 단말/일자 간 비유일(재사용) 가능 → 서로 다른 거래를 오결합.
//       · tid 는 단말(terminal) 단위 식별자 → 같은 단말의 모든 결제를 오결합(최악).
//     DA 는 (a)approval_no-only / (b)tid-only 이분법을 모두 기각.
//
//   ▸ 정답: 3단 캐스케이드로 재정의.
//     ① trxid-exact (1급 키): raw.external_trxid === p.external_trxid
//         · 오늘 inert — isUnmatchedCrm 이 p.external_trxid=null 을 요구하므로 현
//           데이터에서는 발화하지 않는다(external_approval_no 0/295, tier0 30일 0건).
//         · direct-capture(단말→CRM 직수집) future-proof + 총괄 'trxid 1급키' 문자준수.
//           inert 이므로 현 auto-match 에 무해(drop 0 · 신규 false-merge 0).
//     ② composite Model A (= 계약 매칭키 canon): 4조건 전부 요구 —
//         approval_no ∧ amount ∧ tid ∧ approved_at 윈도.
//         · 윈도는 신규 발명 금지(contract §789 그림자윈도 ban) → 기존 Tier1 forward
//           윈도 [approved_at, approved_at+15min] 를 재사용.
//         · = Tier1 predicate ∧ approval_no 일치 = Tier1 고신뢰 부분집합.
//     ③ bare approval_no 가지·bare tid 가지 둘 다 삭제.
//
//   ★ 불변식(영구 고정): 단일키(approval_no 단독 / tid 단독) auto-link 금지.
//     tid 는 composite 구성요소 + Tier1/2 whitelist 로만 생존한다.
//   ★ future note: external_approval_no 채워진 뒤 composite 불충족분은 auto-link 대신
//     하위 Tier/tier4_manual(수동큐)로 fail-safe 강등 = 의도된 안전동작(손실 아님).
/**
 * 직접 키 매칭 (3단 캐스케이드). 매칭은 보너스 — 없으면 하위 Tier 로 진행.
 */
export function findTier0Direct(
  raw:      RawTransaction,
  payments: CrmPayment[]
): CrmPayment[] {
  // ── ① trxid-exact (1급, 오늘 inert — direct-capture future-proof) ─────────
  if (raw.external_trxid) {
    const byTrxid = payments.filter(
      (p) =>
        isUnmatchedCrm(p) &&
        p.external_trxid !== null &&
        p.external_trxid === raw.external_trxid
    );
    if (byTrxid.length > 0) return byTrxid;
  }

  // ── ② composite Model A: approval_no ∧ amount ∧ tid ∧ approved_at 윈도 ──────
  //    4조건 중 하나라도 불충족이면 auto-link 하지 않는다(→ 하위 Tier/manual).
  const hasApproval = Boolean(raw.approval_no);
  const hasTid      = Boolean(raw.tid);
  if (!hasApproval || !hasTid || !raw.approved_at) return [];

  const approvedMs = new Date(raw.approved_at).getTime();

  return payments.filter((p) => {
    if (!isUnmatchedCrm(p)) return false;
    // approval_no 일치 (단독으로는 링크 금지 — 아래 조건과 AND)
    if (p.external_approval_no === null || p.external_approval_no !== raw.approval_no) return false;
    // tid 일치 (composite 구성요소로만 사용)
    if (p.external_tid === null || p.external_tid !== raw.tid) return false;
    // amount 일치
    if (p.amount !== raw.amount) return false;
    // approved_at forward 윈도 [approved_at, +15min] (Tier1 윈도 재사용)
    if (!p.created_at) return false;
    const crmMs = new Date(p.created_at).getTime();
    return crmMs >= approvedMs && crmMs <= approvedMs + TIER1_WINDOW_MS;
  });
}

// ── Tier 1 — Tight 매칭 (단방향 [approved_at, +15분]) ────────────────────────
/**
 * TID whitelist + card + amount + [approved_at, approved_at+15min].
 * 단일 후보이면 매칭. 복수이면 Tier 4.
 * (풋: source_system 필터 없음 — 단일 도메인)
 */
export function findTier1Tight(
  raw:          RawTransaction,
  payments:     CrmPayment[],
  tidWhitelist: Set<string>
): CrmPayment[] {
  if (!raw.tid || !tidWhitelist.has(raw.tid)) return [];
  if (!raw.approved_at) return [];

  const approvedMs = new Date(raw.approved_at).getTime();

  return payments.filter((p) => {
    if (!isUnmatchedCrm(p)) return false;
    if (p.method !== "card") return false;
    if (p.payment_type !== "payment") return false;
    if (p.amount !== raw.amount) return false;
    if (!p.created_at) return false;

    const crmMs = new Date(p.created_at).getTime();
    return crmMs >= approvedMs && crmMs <= approvedMs + TIER1_WINDOW_MS;
  });
}

// ── Tier 2 — Loose 매칭 (단방향 [approved_at, +30분]) ────────────────────────
/**
 * Tier 1과 동일 조건, 시간 윈도만 +30분으로 확장.
 * 단일 후보이면 매칭. 복수이면 Tier 4(multi_candidate).
 */
export function findTier2Loose(
  raw:          RawTransaction,
  payments:     CrmPayment[],
  tidWhitelist: Set<string>
): CrmPayment[] {
  if (!raw.tid || !tidWhitelist.has(raw.tid)) return [];
  if (!raw.approved_at) return [];

  const approvedMs = new Date(raw.approved_at).getTime();

  return payments.filter((p) => {
    if (!isUnmatchedCrm(p)) return false;
    if (p.method !== "card") return false;
    if (p.payment_type !== "payment") return false;
    if (p.amount !== raw.amount) return false;
    if (!p.created_at) return false;

    const crmMs = new Date(p.created_at).getTime();
    return crmMs >= approvedMs && crmMs <= approvedMs + TIER2_WINDOW_MS;
  });
}

// ── Tier 3 — Daily Unique Fallback (KST 같은 날짜 + amount unique) ────────────
/**
 * KST 동일 날짜 + 금액 일치 + unique.
 * 같은 날 동일 금액이 정확히 1건이면 매칭.
 * TID whitelist 불필요 (날짜+금액 unique이면 단말기 식별 불필요).
 */
export function findTier3DailyUnique(
  raw:      RawTransaction,
  payments: CrmPayment[]
): CrmPayment[] {
  if (!raw.approved_at) return [];

  const rawDateKst = toKstDateStr(raw.approved_at);

  return payments.filter((p) => {
    if (!isUnmatchedCrm(p)) return false;
    if (p.method !== "card") return false;
    if (p.payment_type !== "payment") return false;
    if (p.amount !== raw.amount) return false;
    if (!p.created_at) return false;

    return toKstDateStr(p.created_at) === rawDateKst;
  });
}

// ── 단건 매칭 (4-Tier 우선순위 적용) ─────────────────────────────────────────
/**
 * 단일 raw 트랜잭션에 대해 4-Tier 매칭 수행.
 *
 * @param raw          - Redpay raw 트랜잭션
 * @param payments     - 비교 대상 CRM 결제 목록 (미매칭 필터링은 각 Tier 함수에서)
 * @param tidWhitelist - Tier 1/2 적용 TID 목록 (env: REDPAY_TID_WHITELIST)
 * @returns MatchResult
 */
export function matchTransaction(
  raw:          RawTransaction,
  payments:     CrmPayment[],
  tidWhitelist: Set<string> = new Set()
): MatchResult {
  // 취소/오류 건은 매칭 제외 (환불 link는 별도 detectRefundNotInCrm)
  if (CANCELLED_STATUSES.has(raw.external_status)) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         null,
      matched:            false,
      needs_manual:       false,
      fail_reason:        `취소/환불 거래 (status=${raw.external_status}) — 매칭 불필요`,
    };
  }

  // ── Tier 0: Direct (보너스) ─────────────────────────────────────────────
  const byDirect = findTier0Direct(raw, payments);
  if (byDirect.length === 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         byDirect[0].id,
      match_rule:         "tier0_direct",
      matched:            true,
      needs_manual:       false,
      fail_reason:        null,
    };
  }
  if (byDirect.length > 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         "tier4_manual",
      matched:            false,
      needs_manual:       true,
      fail_reason:        `tier0 멀티 후보 ${byDirect.length}건 — 수동 확인 필요`,
    };
  }

  // ── Tier 1: Tight (단방향 +15분) ──────────────────────────────────────
  const byTier1 = findTier1Tight(raw, payments, tidWhitelist);
  if (byTier1.length === 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         byTier1[0].id,
      match_rule:         "tier1_tight",
      matched:            true,
      needs_manual:       false,
      fail_reason:        null,
    };
  }
  if (byTier1.length > 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         "tier4_manual",
      matched:            false,
      needs_manual:       true,
      fail_reason:        `tier1 멀티 후보 ${byTier1.length}건 (±15min) — 수동 매칭 큐`,
    };
  }

  // ── Tier 2: Loose (단방향 +30분) ──────────────────────────────────────
  const byTier2 = findTier2Loose(raw, payments, tidWhitelist);
  if (byTier2.length === 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         byTier2[0].id,
      match_rule:         "tier2_loose",
      matched:            true,
      needs_manual:       false,
      fail_reason:        null,
    };
  }
  if (byTier2.length > 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         "tier4_manual",
      matched:            false,
      needs_manual:       true,
      fail_reason:        `tier2 멀티 후보 ${byTier2.length}건 (±30min) — 수동 매칭 큐`,
    };
  }

  // ── Tier 3: Daily Unique ──────────────────────────────────────────────
  const byTier3 = findTier3DailyUnique(raw, payments);
  if (byTier3.length === 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         byTier3[0].id,
      match_rule:         "tier3_daily_unique",
      matched:            true,
      needs_manual:       false,
      fail_reason:        null,
    };
  }
  if (byTier3.length > 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         "tier4_manual",
      matched:            false,
      needs_manual:       true,
      fail_reason:        `tier3 멀티 후보 ${byTier3.length}건 (daily) — 수동 매칭 큐`,
    };
  }

  // ── Tier 4: 수동 매칭 큐 ─────────────────────────────────────────────
  return {
    raw_transaction_id: raw.id,
    payment_id:         null,
    match_rule:         "tier4_manual",
    matched:            false,
    needs_manual:       true,
    fail_reason:        "자동 매칭 후보 없음 — 수동 매칭 필요",
  };
}

// ── 배치 매칭 (이중 매칭 방지 포함) ──────────────────────────────────────────
/**
 * 다수 raw 트랜잭션에 대해 배치 매칭.
 * 이중 매칭 방지: matchedPaymentIds Set으로 이미 매칭된 CRM payment 제외.
 *
 * @param rawList      - Redpay raw 트랜잭션 목록 (미매칭 Y 건만)
 * @param crmPayments  - CRM 결제 목록 (미매칭 pool)
 * @param tidWhitelist - Tier 1/2 TID 화이트리스트
 * @returns MatchResult[]
 */
export function matchTransactionsBatch(
  rawList:      RawTransaction[],
  crmPayments:  CrmPayment[],
  tidWhitelist: Set<string>
): MatchResult[] {
  const matchedPaymentIds = new Set<string>(); // 이미 매칭된 CRM payment ID
  const results: MatchResult[] = [];

  for (const raw of rawList) {
    const availablePayments = crmPayments.filter(
      (p) => !matchedPaymentIds.has(p.id)
    );

    const result = matchTransaction(raw, availablePayments, tidWhitelist);
    results.push(result);

    if (result.matched && result.payment_id) {
      matchedPaymentIds.add(result.payment_id);
    }
  }

  return results;
}

// ── 이상 탐지 (AC-3) ─────────────────────────────────────────────────────────

/**
 * missing_in_crm 탐지.
 * redpay에 있고 status=Y(승인)인데 CRM에 매칭된 결제가 없는 경우.
 */
export function detectMissingInCrm(
  rawList:       RawTransaction[],
  targetChannel: string
): ReconEvent[] {
  return rawList
    .filter(
      (r) =>
        r.external_status === "Y" &&
        r.matched_payment_id === null
    )
    .map((r) => ({
      clinic_id:          r.clinic_id,
      raw_transaction_id: r.id,
      payment_id:         null,
      event_type:         "missing_in_crm" as const,
      match_rule:         null,
      mismatch_reason:    "redpay 승인거래(Y) — CRM 결제 레코드 없음",
      external_trxid:     r.external_trxid,
      external_amount:    r.amount,
      crm_amount:         null,
      alert_payload: buildAlertPayload(
        "missing_in_crm",
        targetChannel,
        r.external_trxid,
        r.amount,
        null,
        r.approved_at,
        "redpay 승인거래(Y) — CRM 결제 레코드 없음"
      ),
    }));
}

/**
 * missing_at_van 탐지.
 * CRM에 결제(payment)가 있지만 reconciled_at이 null이고 created_at이 현재 기준
 * 30분 이상 지난 경우 → redpay에서 확인 불가.
 */
export function detectMissingAtVan(
  crmPayments:   CrmPayment[],
  now:           Date,
  targetChannel: string,
  cooldownMs     = 30 * 60 * 1000
): ReconEvent[] {
  return crmPayments
    .filter((p) => {
      if (p.payment_type !== "payment") return false;
      if (p.reconciled_at !== null) return false;
      if (!p.created_at) return false;
      const pTime = new Date(p.created_at).getTime();
      return now.getTime() - pTime > cooldownMs;
    })
    .map((p) => ({
      clinic_id:          p.clinic_id,
      raw_transaction_id: null,
      payment_id:         p.id,
      event_type:         "missing_at_van" as const,
      match_rule:         null,
      mismatch_reason:    `CRM 결제 있음 — redpay 거래 없음 (${cooldownMs / 60000}분 쿨다운 경과)`,
      external_trxid:     null,
      external_amount:    null,
      crm_amount:         p.amount,
      alert_payload: buildAlertPayload(
        "missing_at_van",
        targetChannel,
        null,
        null,
        p.amount,
        p.created_at,
        "CRM 결제 있음 — redpay 거래 없음"
      ),
    }));
}

/**
 * amount_mismatch 탐지.
 * raw와 CRM 결제가 매칭되었지만 금액이 다른 경우.
 */
export function detectAmountMismatch(
  raw:           RawTransaction,
  payment:       CrmPayment,
  targetChannel: string
): ReconEvent | null {
  if (raw.amount === payment.amount) return null;

  return {
    clinic_id:          raw.clinic_id,
    raw_transaction_id: raw.id,
    payment_id:         payment.id,
    event_type:         "amount_mismatch",
    match_rule:         null,
    mismatch_reason:    `redpay=${raw.amount}원 CRM=${payment.amount}원`,
    external_trxid:     raw.external_trxid,
    external_amount:    raw.amount,
    crm_amount:         payment.amount,
    alert_payload: buildAlertPayload(
      "amount_mismatch",
      targetChannel,
      raw.external_trxid,
      raw.amount,
      payment.amount,
      raw.approved_at,
      `redpay=${raw.amount}원 CRM=${payment.amount}원`
    ),
  };
}

/**
 * refund_not_in_crm 탐지.
 * redpay 거래 status가 N/X/M(취소·오류·부분취소)이고
 * root_trxid로 연결된 원거래 CRM 결제가 취소되지 않은 경우.
 */
export function detectRefundNotInCrm(
  raw:          RawTransaction,
  crmPayments:  CrmPayment[],
  targetChannel: string
): ReconEvent | null {
  if (!CANCELLED_STATUSES.has(raw.external_status)) return null;

  const rootId = raw.root_trxid ?? raw.external_trxid;
  const original = crmPayments.find(
    (p) =>
      p.external_trxid === rootId &&
      p.payment_type === "payment" &&
      p.reconciled_at !== null
  );

  if (!original) return null;

  return {
    clinic_id:          raw.clinic_id,
    raw_transaction_id: raw.id,
    payment_id:         original.id,
    event_type:         "refund_not_in_crm",
    match_rule:         null,
    mismatch_reason:    `redpay 취소(${raw.external_status}) — CRM 결제 환불 미반영`,
    external_trxid:     raw.external_trxid,
    external_amount:    raw.amount,
    crm_amount:         original.amount,
    alert_payload: buildAlertPayload(
      "refund_not_in_crm",
      targetChannel,
      raw.external_trxid,
      raw.amount,
      original.amount,
      raw.approved_at,
      `redpay 취소(${raw.external_status}) — CRM 결제 환불 미반영`
    ),
  };
}

// ── 알림 페이로드 빌더 ───────────────────────────────────────────────────────
export function buildAlertPayload(
  alertType:      AlertPayload["alert_type"],
  targetChannel:  string,
  externalTrxid:  string | null,
  externalAmount: number | null,
  crmAmount:      number | null,
  approvedAt:     string | null,
  mismatchReason: string | null
): AlertPayload {
  return {
    alert_type:      alertType,
    target_channel:  targetChannel,
    external_trxid:  externalTrxid,
    external_amount: externalAmount,
    crm_amount:      crmAmount,
    approved_at:     approvedAt,
    mismatch_reason: mismatchReason,
  };
}

/**
 * 알림 페이로드 → Slack 메시지 텍스트 포맷팅.
 */
export function formatAlertMessage(payload: AlertPayload): string {
  const amtStr = (v: number | null) =>
    v !== null ? `${v.toLocaleString()}원` : "?";
  const trxStr = payload.external_trxid ?? "UNKNOWN";
  const timeStr = payload.approved_at
    ? new Date(payload.approved_at).toLocaleString("ko-KR", { timeZone: "Asia/Seoul" })
    : "";

  switch (payload.alert_type) {
    case "missing_in_crm":
      return (
        `🚨 *[결제 누락]* 단말기 결제가 CRM에 없습니다.\n` +
        `• 거래 ID: ${trxStr}\n` +
        `• 금액: ${amtStr(payload.external_amount)}\n` +
        `• 승인시각: ${timeStr}\n` +
        `→ CRM에서 해당 결제 확인 후 수동 입력 바랍니다.`
      );
    case "missing_at_van":
      return (
        `⚠️ *[단말기 누락]* CRM 결제가 단말기에서 확인되지 않습니다.\n` +
        `• CRM 결제 금액: ${amtStr(payload.crm_amount)}\n` +
        `• 결제 시각: ${timeStr}\n` +
        `→ 단말기 거래 내역과 대조 바랍니다.`
      );
    case "amount_mismatch":
      return (
        `⚠️ *[금액 불일치]* 단말기와 CRM 금액이 다릅니다.\n` +
        `• 거래 ID: ${trxStr}\n` +
        `• 단말기: ${amtStr(payload.external_amount)} / CRM: ${amtStr(payload.crm_amount)}\n` +
        `• 승인시각: ${timeStr}\n` +
        `→ 차이: ${payload.external_amount !== null && payload.crm_amount !== null ? amtStr(Math.abs(payload.external_amount - payload.crm_amount)) : "?"}`
      );
    case "refund_not_in_crm":
      return (
        `🔴 *[취소 미반영]* 단말기 취소가 CRM에 반영되지 않았습니다.\n` +
        `• 거래 ID: ${trxStr}\n` +
        `• 취소 금액: ${amtStr(payload.external_amount)}\n` +
        `• 취소 시각: ${timeStr}\n` +
        `→ CRM에서 해당 결제 취소 처리가 필요합니다.`
      );
    default:
      return `[reconciliation 알림] ${payload.alert_type}: ${payload.mismatch_reason ?? ""}`;
  }
}

// ── reconciliation_log state-change 게이트 (T-20260725-foot-REDPAY-RECONLOG-IDEMPOTENCY) ──
//   지속-미매칭 raw 가 사이클마다 match_failed/missing_in_crm 를 '무-상태변화'로 재생성 →
//   로그 무한증식 + count 인플레(forensic816: 1 raw→816행). raw별 '직전 로그 event_type' 과
//   diff 하여 상태 전이(transition/최초관측) 시에만 insert 한다. append-only 시맨틱 보존.
//   억제 대상은 아래 두 타입에 한정 — auto_matched 는 terminal 이라 억제 비대상.
export const SUPPRESSIBLE_EVENT_TYPES: ReadonlySet<string> = new Set([
  "match_failed",
  "missing_in_crm",
]);

/**
 * 순수 술어: recon 이벤트 배열 + raw별 '직전 로그 event_type' 맵을 받아
 * 실제 insert 할 이벤트와 억제(무-상태변화) 건수를 계산한다. DB I/O 없음.
 *
 * · 억제 대상 타입(match_failed/missing_in_crm) 이면서 raw_transaction_id 가 있고,
 *   직전 로그 event_type 이 현재와 동일하면 → 억제(전이 아님).
 * · 그 외(비억제 타입, raw 없는 이벤트, 전이/최초관측) → insert.
 * · 배치-내 상태도 갱신 → 같은 사이클 내 동일 raw·동일타입 중복도 1건으로 억제.
 *
 * @param events          이번 사이클 recon 이벤트
 * @param priorEventType  raw_transaction_id → 직전 로그 event_type (append-only 최신 1건)
 */
export function planReconLogInserts(
  events: ReconEvent[],
  priorEventType: Map<string, string>,
): { toInsert: ReconEvent[]; suppressed: number } {
  // priorEventType 를 배치-내에서 변형하지 않도록 로컬 복제.
  const seen = new Map<string, string>(priorEventType);
  let suppressed = 0;
  const toInsert = events.filter((e) => {
    if (!(e.raw_transaction_id && SUPPRESSIBLE_EVENT_TYPES.has(e.event_type))) {
      return true; // 비억제 타입 / raw 없는 이벤트 → 무조건 insert
    }
    const prev = seen.get(e.raw_transaction_id);
    if (prev === e.event_type) {
      suppressed++;
      return false; // 무-상태변화 → 억제
    }
    seen.set(e.raw_transaction_id, e.event_type); // 전이 확정 → 배치-내 갱신
    return true;
  });
  return { toInsert, suppressed };
}
