// T-20260607-foot-REDPAY-PORT — Reconciliation 매칭 엔진 (4-Tier) 풋센터 이식
//
// 출처: T-20260520-crm-PAY-RECON-001 M2 (롱레CRM 검증 완료). 풋 변형 적용.
// 순수 함수 모듈. Supabase / Deno 의존 없음 → vitest 단위 테스트 가능.
//
// ── 풋 변형 (롱레와 다른 점) ─────────────────────────────────────────────────
//   롱레는 단일 DB에 longlasting/vegas 다출처 payments 가 섞여 source_system 으로
//   분리했으나, 풋CRM payments 에는 source_system 컬럼이 없음(단일 도메인).
//   → Tier 1/2/3 의 source_system 필터 제거. card + payment + amount + 시간 윈도로 매칭.
//
// ── 개발 목적 본질 (대표 직접 지시 2026-05-26) ─────────────────────────────────
//   직원이 결제할 때 결제번호를 넣는 불편함을 줄이는 게 핵심.
//   결제 시간·시점·금액 정보 기반 자동 매칭.
//   승인번호·TID 입력은 보너스(있으면 우선, 없어도 매칭 시도).
//
// ── 4-Tier 매칭 우선순위 ──────────────────────────────────────────────────────
//   Tier 0  — Direct (보너스): external_approval_no / external_tid 직접 일치
//   Tier 1  — Tight (95% 목표): tid whitelist + card + amount + [+15min]
//   Tier 2  — Loose: 같은 조건 + [+30min], single candidate만 매칭
//   Tier 3  — Daily Unique: KST 같은 날짜 + amount unique
//   Tier 4  — Manual: 수동 매칭 큐 (multi_candidate or fallback)
//
// ── 시간 방향 (단방향 +방향) ─────────────────────────────────────────────────
//   redpay.approved_at  = 단말기 승인 시각 (먼저)
//   CRM.created_at      = 직원이 CRM에 입력한 시각 (나중)
//   윈도: [approved_at, approved_at + N분]
//
// ── 알림 카테고리 (AC-3) ─────────────────────────────────────────────────────
//   'missing_in_crm'    — 단말기 ○ CRM ✕ (매출 분실 위험)
//   'missing_at_van'    — CRM ○ 단말기 ✕
//   'amount_mismatch'   — 양쪽 있지만 금액 다름
//   'refund_not_in_crm' — 단말기 취소 CRM active

// ── 타입 ────────────────────────────────────────────────────────────────────

/** Redpay raw_transactions 레코드 (DB 칼럼과 1:1) */
export interface RawTransaction {
  id:              string;
  clinic_id:       string;
  external_trxid:  string;
  external_status: string;   // Y=승인 N=취소 M=부분취소 X=오류
  amount:          number;
  approval_no:     string | null;
  root_trxid:      string | null;
  tid:             string | null;
  approved_at:     string | null;  // ISO8601 UTC
  matched_payment_id: string | null;
}

/** CRM payments 레코드 (reconciliation에 필요한 필드만)
 *
 * 주의: DB 실컬럼은 paid_at이 없고 created_at만 있음.
 * created_at = 직원이 결제를 CRM에 입력한 시각 (auto-generated by DB).
 * source_system: 풋CRM 에는 없음 → optional (매칭 로직 미사용).
 */
export interface CrmPayment {
  id:              string;
  clinic_id:       string;
  amount:          number;
  method:          string;   // 'card' | 'cash' | 'transfer' | 'membership'
  payment_type:    string;   // 'payment' | 'refund'
  source_system?:  string;   // 풋: 미사용 (호환 위해 optional 보존)
  created_at:      string | null;  // ISO8601 UTC — 직원 입력 시각
  external_trxid:  string | null;
  external_approval_no: string | null;
  external_tid:    string | null;
  reconciled_at:   string | null;  // null = 미매칭
}

/** 매칭 결과 단건 */
export interface MatchResult {
  raw_transaction_id: string;
  payment_id:         string | null;
  match_rule:
    | "tier0_direct"
    | "tier1_tight"
    | "tier2_loose"
    | "tier3_daily_unique"
    | "tier4_manual"
    | null;
  /** 자동 매칭 성공 여부 */
  matched:       boolean;
  /** 수동 매칭 큐로 이관 여부 */
  needs_manual:  boolean;
  /** 매칭 실패 사유 */
  fail_reason:   string | null;
}

/** reconciliation_log 이벤트 페이로드 (DB insert 직전) */
export interface ReconEvent {
  clinic_id:          string;
  raw_transaction_id: string | null;
  payment_id:         string | null;
  event_type:
    | "auto_matched"
    | "match_failed"
    | "missing_in_crm"
    | "missing_at_van"
    | "amount_mismatch"
    | "refund_not_in_crm";
  match_rule:
    | "tier0_direct"
    | "tier1_tight"
    | "tier2_loose"
    | "tier3_daily_unique"
    | "tier4_manual"
    | null;
  mismatch_reason: string | null;
  external_trxid:  string | null;
  external_amount: number | null;
  crm_amount:      number | null;
  /** 알림 페이로드 (실발송은 M3 이후 — M0에서는 로그만) */
  alert_payload:   AlertPayload | null;
}

/** Slack 알림 페이로드 (M3에서 실발송) */
export interface AlertPayload {
  alert_type:       ReconEvent["event_type"];
  target_channel:   string;
  external_trxid:   string | null;
  external_amount:  number | null;
  crm_amount:       number | null;
  approved_at:      string | null;
  mismatch_reason:  string | null;
}

// ── 상수 ────────────────────────────────────────────────────────────────────

/** Tier 1 단방향 윈도: [approved_at, +15분] */
export const TIER1_WINDOW_MS = 15 * 60 * 1000;

/** Tier 2 단방향 윈도: [approved_at, +30분] */
export const TIER2_WINDOW_MS = 30 * 60 * 1000;

/** 환불/취소 상태 목록 */
export const CANCELLED_STATUSES = new Set(["N", "X", "M"]);

// ── 헬퍼 ─────────────────────────────────────────────────────────────────────

/**
 * ISO8601 UTC 문자열 → KST 날짜 문자열 (YYYY-MM-DD).
 * 타임존 오프셋 없이 단순 +9h 연산.
 */
export function toKstDateStr(isoUtc: string): string {
  const ms = new Date(isoUtc).getTime();
  const kstMs = ms + 9 * 60 * 60 * 1000;
  return new Date(kstMs).toISOString().slice(0, 10);
}

/**
 * CRM payment가 매칭 가능한 상태인지 확인.
 * reconciled_at IS NULL AND external_trxid IS NULL
 */
function isUnmatchedCrm(p: CrmPayment): boolean {
  return p.reconciled_at === null && p.external_trxid === null;
}

// ── Tier 0 — Direct 매칭 (보너스: 직원이 어쩌다 승인번호/TID 입력한 경우) ────────
/**
 * 직접 키 매칭.
 * external_approval_no 또는 external_tid가 CRM에 입력된 경우 우선 매칭.
 * 의무 아님 — 없으면 Tier 1로.
 */
export function findTier0Direct(
  raw:      RawTransaction,
  payments: CrmPayment[]
): CrmPayment[] {
  const hasApproval = Boolean(raw.approval_no);
  const hasTid      = Boolean(raw.tid);
  if (!hasApproval && !hasTid) return [];

  return payments.filter((p) => {
    if (!isUnmatchedCrm(p)) return false;
    if (hasApproval && p.external_approval_no !== null && p.external_approval_no === raw.approval_no) {
      return true;
    }
    if (hasTid && p.external_tid !== null && p.external_tid === raw.tid) {
      return true;
    }
    return false;
  });
}

// ── Tier 1 — Tight 매칭 (단방향 [approved_at, +15분]) ────────────────────────
/**
 * TID whitelist + card + amount + [approved_at, approved_at+15min].
 * 단일 후보이면 매칭. 복수이면 Tier 4.
 * (풋: source_system 필터 없음 — 단일 도메인)
 */
export function findTier1Tight(
  raw:          RawTransaction,
  payments:     CrmPayment[],
  tidWhitelist: Set<string>
): CrmPayment[] {
  if (!raw.tid || !tidWhitelist.has(raw.tid)) return [];
  if (!raw.approved_at) return [];

  const approvedMs = new Date(raw.approved_at).getTime();

  return payments.filter((p) => {
    if (!isUnmatchedCrm(p)) return false;
    if (p.method !== "card") return false;
    if (p.payment_type !== "payment") return false;
    if (p.amount !== raw.amount) return false;
    if (!p.created_at) return false;

    const crmMs = new Date(p.created_at).getTime();
    return crmMs >= approvedMs && crmMs <= approvedMs + TIER1_WINDOW_MS;
  });
}

// ── Tier 2 — Loose 매칭 (단방향 [approved_at, +30분]) ────────────────────────
/**
 * Tier 1과 동일 조건, 시간 윈도만 +30분으로 확장.
 * 단일 후보이면 매칭. 복수이면 Tier 4(multi_candidate).
 */
export function findTier2Loose(
  raw:          RawTransaction,
  payments:     CrmPayment[],
  tidWhitelist: Set<string>
): CrmPayment[] {
  if (!raw.tid || !tidWhitelist.has(raw.tid)) return [];
  if (!raw.approved_at) return [];

  const approvedMs = new Date(raw.approved_at).getTime();

  return payments.filter((p) => {
    if (!isUnmatchedCrm(p)) return false;
    if (p.method !== "card") return false;
    if (p.payment_type !== "payment") return false;
    if (p.amount !== raw.amount) return false;
    if (!p.created_at) return false;

    const crmMs = new Date(p.created_at).getTime();
    return crmMs >= approvedMs && crmMs <= approvedMs + TIER2_WINDOW_MS;
  });
}

// ── Tier 3 — Daily Unique Fallback (KST 같은 날짜 + amount unique) ────────────
/**
 * KST 동일 날짜 + 금액 일치 + unique.
 * 같은 날 동일 금액이 정확히 1건이면 매칭.
 * TID whitelist 불필요 (날짜+금액 unique이면 단말기 식별 불필요).
 */
export function findTier3DailyUnique(
  raw:      RawTransaction,
  payments: CrmPayment[]
): CrmPayment[] {
  if (!raw.approved_at) return [];

  const rawDateKst = toKstDateStr(raw.approved_at);

  return payments.filter((p) => {
    if (!isUnmatchedCrm(p)) return false;
    if (p.method !== "card") return false;
    if (p.payment_type !== "payment") return false;
    if (p.amount !== raw.amount) return false;
    if (!p.created_at) return false;

    return toKstDateStr(p.created_at) === rawDateKst;
  });
}

// ── 단건 매칭 (4-Tier 우선순위 적용) ─────────────────────────────────────────
/**
 * 단일 raw 트랜잭션에 대해 4-Tier 매칭 수행.
 *
 * @param raw          - Redpay raw 트랜잭션
 * @param payments     - 비교 대상 CRM 결제 목록 (미매칭 필터링은 각 Tier 함수에서)
 * @param tidWhitelist - Tier 1/2 적용 TID 목록 (env: REDPAY_TID_WHITELIST)
 * @returns MatchResult
 */
export function matchTransaction(
  raw:          RawTransaction,
  payments:     CrmPayment[],
  tidWhitelist: Set<string> = new Set()
): MatchResult {
  // 취소/오류 건은 매칭 제외 (환불 link는 별도 detectRefundNotInCrm)
  if (CANCELLED_STATUSES.has(raw.external_status)) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         null,
      matched:            false,
      needs_manual:       false,
      fail_reason:        `취소/환불 거래 (status=${raw.external_status}) — 매칭 불필요`,
    };
  }

  // ── Tier 0: Direct (보너스) ─────────────────────────────────────────────
  const byDirect = findTier0Direct(raw, payments);
  if (byDirect.length === 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         byDirect[0].id,
      match_rule:         "tier0_direct",
      matched:            true,
      needs_manual:       false,
      fail_reason:        null,
    };
  }
  if (byDirect.length > 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         "tier4_manual",
      matched:            false,
      needs_manual:       true,
      fail_reason:        `tier0 멀티 후보 ${byDirect.length}건 — 수동 확인 필요`,
    };
  }

  // ── Tier 1: Tight (단방향 +15분) ──────────────────────────────────────
  const byTier1 = findTier1Tight(raw, payments, tidWhitelist);
  if (byTier1.length === 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         byTier1[0].id,
      match_rule:         "tier1_tight",
      matched:            true,
      needs_manual:       false,
      fail_reason:        null,
    };
  }
  if (byTier1.length > 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         "tier4_manual",
      matched:            false,
      needs_manual:       true,
      fail_reason:        `tier1 멀티 후보 ${byTier1.length}건 (±15min) — 수동 매칭 큐`,
    };
  }

  // ── Tier 2: Loose (단방향 +30분) ──────────────────────────────────────
  const byTier2 = findTier2Loose(raw, payments, tidWhitelist);
  if (byTier2.length === 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         byTier2[0].id,
      match_rule:         "tier2_loose",
      matched:            true,
      needs_manual:       false,
      fail_reason:        null,
    };
  }
  if (byTier2.length > 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         "tier4_manual",
      matched:            false,
      needs_manual:       true,
      fail_reason:        `tier2 멀티 후보 ${byTier2.length}건 (±30min) — 수동 매칭 큐`,
    };
  }

  // ── Tier 3: Daily Unique ──────────────────────────────────────────────
  const byTier3 = findTier3DailyUnique(raw, payments);
  if (byTier3.length === 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         byTier3[0].id,
      match_rule:         "tier3_daily_unique",
      matched:            true,
      needs_manual:       false,
      fail_reason:        null,
    };
  }
  if (byTier3.length > 1) {
    return {
      raw_transaction_id: raw.id,
      payment_id:         null,
      match_rule:         "tier4_manual",
      matched:            false,
      needs_manual:       true,
      fail_reason:        `tier3 멀티 후보 ${byTier3.length}건 (daily) — 수동 매칭 큐`,
    };
  }

  // ── Tier 4: 수동 매칭 큐 ─────────────────────────────────────────────
  return {
    raw_transaction_id: raw.id,
    payment_id:         null,
    match_rule:         "tier4_manual",
    matched:            false,
    needs_manual:       true,
    fail_reason:        "자동 매칭 후보 없음 — 수동 매칭 필요",
  };
}

// ── 배치 매칭 (이중 매칭 방지 포함) ──────────────────────────────────────────
/**
 * 다수 raw 트랜잭션에 대해 배치 매칭.
 * 이중 매칭 방지: matchedPaymentIds Set으로 이미 매칭된 CRM payment 제외.
 *
 * @param rawList      - Redpay raw 트랜잭션 목록 (미매칭 Y 건만)
 * @param crmPayments  - CRM 결제 목록 (미매칭 pool)
 * @param tidWhitelist - Tier 1/2 TID 화이트리스트
 * @returns MatchResult[]
 */
export function matchTransactionsBatch(
  rawList:      RawTransaction[],
  crmPayments:  CrmPayment[],
  tidWhitelist: Set<string>
): MatchResult[] {
  const matchedPaymentIds = new Set<string>(); // 이미 매칭된 CRM payment ID
  const results: MatchResult[] = [];

  for (const raw of rawList) {
    const availablePayments = crmPayments.filter(
      (p) => !matchedPaymentIds.has(p.id)
    );

    const result = matchTransaction(raw, availablePayments, tidWhitelist);
    results.push(result);

    if (result.matched && result.payment_id) {
      matchedPaymentIds.add(result.payment_id);
    }
  }

  return results;
}

// ── 이상 탐지 (AC-3) ─────────────────────────────────────────────────────────

/**
 * missing_in_crm 탐지.
 * redpay에 있고 status=Y(승인)인데 CRM에 매칭된 결제가 없는 경우.
 */
export function detectMissingInCrm(
  rawList:       RawTransaction[],
  targetChannel: string
): ReconEvent[] {
  return rawList
    .filter(
      (r) =>
        r.external_status === "Y" &&
        r.matched_payment_id === null
    )
    .map((r) => ({
      clinic_id:          r.clinic_id,
      raw_transaction_id: r.id,
      payment_id:         null,
      event_type:         "missing_in_crm" as const,
      match_rule:         null,
      mismatch_reason:    "redpay 승인거래(Y) — CRM 결제 레코드 없음",
      external_trxid:     r.external_trxid,
      external_amount:    r.amount,
      crm_amount:         null,
      alert_payload: buildAlertPayload(
        "missing_in_crm",
        targetChannel,
        r.external_trxid,
        r.amount,
        null,
        r.approved_at,
        "redpay 승인거래(Y) — CRM 결제 레코드 없음"
      ),
    }));
}

/**
 * missing_at_van 탐지.
 * CRM에 결제(payment)가 있지만 reconciled_at이 null이고 created_at이 현재 기준
 * 30분 이상 지난 경우 → redpay에서 확인 불가.
 */
export function detectMissingAtVan(
  crmPayments:   CrmPayment[],
  now:           Date,
  targetChannel: string,
  cooldownMs     = 30 * 60 * 1000
): ReconEvent[] {
  return crmPayments
    .filter((p) => {
      if (p.payment_type !== "payment") return false;
      if (p.reconciled_at !== null) return false;
      if (!p.created_at) return false;
      const pTime = new Date(p.created_at).getTime();
      return now.getTime() - pTime > cooldownMs;
    })
    .map((p) => ({
      clinic_id:          p.clinic_id,
      raw_transaction_id: null,
      payment_id:         p.id,
      event_type:         "missing_at_van" as const,
      match_rule:         null,
      mismatch_reason:    `CRM 결제 있음 — redpay 거래 없음 (${cooldownMs / 60000}분 쿨다운 경과)`,
      external_trxid:     null,
      external_amount:    null,
      crm_amount:         p.amount,
      alert_payload: buildAlertPayload(
        "missing_at_van",
        targetChannel,
        null,
        null,
        p.amount,
        p.created_at,
        "CRM 결제 있음 — redpay 거래 없음"
      ),
    }));
}

/**
 * amount_mismatch 탐지.
 * raw와 CRM 결제가 매칭되었지만 금액이 다른 경우.
 */
export function detectAmountMismatch(
  raw:           RawTransaction,
  payment:       CrmPayment,
  targetChannel: string
): ReconEvent | null {
  if (raw.amount === payment.amount) return null;

  return {
    clinic_id:          raw.clinic_id,
    raw_transaction_id: raw.id,
    payment_id:         payment.id,
    event_type:         "amount_mismatch",
    match_rule:         null,
    mismatch_reason:    `redpay=${raw.amount}원 CRM=${payment.amount}원`,
    external_trxid:     raw.external_trxid,
    external_amount:    raw.amount,
    crm_amount:         payment.amount,
    alert_payload: buildAlertPayload(
      "amount_mismatch",
      targetChannel,
      raw.external_trxid,
      raw.amount,
      payment.amount,
      raw.approved_at,
      `redpay=${raw.amount}원 CRM=${payment.amount}원`
    ),
  };
}

/**
 * refund_not_in_crm 탐지.
 * redpay 거래 status가 N/X/M(취소·오류·부분취소)이고
 * root_trxid로 연결된 원거래 CRM 결제가 취소되지 않은 경우.
 */
export function detectRefundNotInCrm(
  raw:          RawTransaction,
  crmPayments:  CrmPayment[],
  targetChannel: string
): ReconEvent | null {
  if (!CANCELLED_STATUSES.has(raw.external_status)) return null;

  const rootId = raw.root_trxid ?? raw.external_trxid;
  const original = crmPayments.find(
    (p) =>
      p.external_trxid === rootId &&
      p.payment_type === "payment" &&
      p.reconciled_at !== null
  );

  if (!original) return null;

  return {
    clinic_id:          raw.clinic_id,
    raw_transaction_id: raw.id,
    payment_id:         original.id,
    event_type:         "refund_not_in_crm",
    match_rule:         null,
    mismatch_reason:    `redpay 취소(${raw.external_status}) — CRM 결제 환불 미반영`,
    external_trxid:     raw.external_trxid,
    external_amount:    raw.amount,
    crm_amount:         original.amount,
    alert_payload: buildAlertPayload(
      "refund_not_in_crm",
      targetChannel,
      raw.external_trxid,
      raw.amount,
      original.amount,
      raw.approved_at,
      `redpay 취소(${raw.external_status}) — CRM 결제 환불 미반영`
    ),
  };
}

// ── 알림 페이로드 빌더 ───────────────────────────────────────────────────────
export function buildAlertPayload(
  alertType:      AlertPayload["alert_type"],
  targetChannel:  string,
  externalTrxid:  string | null,
  externalAmount: number | null,
  crmAmount:      number | null,
  approvedAt:     string | null,
  mismatchReason: string | null
): AlertPayload {
  return {
    alert_type:      alertType,
    target_channel:  targetChannel,
    external_trxid:  externalTrxid,
    external_amount: externalAmount,
    crm_amount:      crmAmount,
    approved_at:     approvedAt,
    mismatch_reason: mismatchReason,
  };
}

/**
 * 알림 페이로드 → Slack 메시지 텍스트 포맷팅.
 */
export function formatAlertMessage(payload: AlertPayload): string {
  const amtStr = (v: number | null) =>
    v !== null ? `${v.toLocaleString()}원` : "?";
  const trxStr = payload.external_trxid ?? "UNKNOWN";
  const timeStr = payload.approved_at
    ? new Date(payload.approved_at).toLocaleString("ko-KR", { timeZone: "Asia/Seoul" })
    : "";

  switch (payload.alert_type) {
    case "missing_in_crm":
      return (
        `🚨 *[결제 누락]* 단말기 결제가 CRM에 없습니다.\n` +
        `• 거래 ID: ${trxStr}\n` +
        `• 금액: ${amtStr(payload.external_amount)}\n` +
        `• 승인시각: ${timeStr}\n` +
        `→ CRM에서 해당 결제 확인 후 수동 입력 바랍니다.`
      );
    case "missing_at_van":
      return (
        `⚠️ *[단말기 누락]* CRM 결제가 단말기에서 확인되지 않습니다.\n` +
        `• CRM 결제 금액: ${amtStr(payload.crm_amount)}\n` +
        `• 결제 시각: ${timeStr}\n` +
        `→ 단말기 거래 내역과 대조 바랍니다.`
      );
    case "amount_mismatch":
      return (
        `⚠️ *[금액 불일치]* 단말기와 CRM 금액이 다릅니다.\n` +
        `• 거래 ID: ${trxStr}\n` +
        `• 단말기: ${amtStr(payload.external_amount)} / CRM: ${amtStr(payload.crm_amount)}\n` +
        `• 승인시각: ${timeStr}\n` +
        `→ 차이: ${payload.external_amount !== null && payload.crm_amount !== null ? amtStr(Math.abs(payload.external_amount - payload.crm_amount)) : "?"}`
      );
    case "refund_not_in_crm":
      return (
        `🔴 *[취소 미반영]* 단말기 취소가 CRM에 반영되지 않았습니다.\n` +
        `• 거래 ID: ${trxStr}\n` +
        `• 취소 금액: ${amtStr(payload.external_amount)}\n` +
        `• 취소 시각: ${timeStr}\n` +
        `→ CRM에서 해당 결제 취소 처리가 필요합니다.`
      );
    default:
      return `[reconciliation 알림] ${payload.alert_type}: ${payload.mismatch_reason ?? ""}`;
  }
}
