-- ROLLBACK for cleanup_bak_20260628110546 (T-20260616-foot-PKG-CUSTNAME-ENCRYPTED)
-- 사용: psql "$DATABASE_URL" -f <this file>   (백업 스키마 cleanup_bak_20260628110546 존재 시에만 유효)
BEGIN;
ALTER TABLE public.customers DISABLE TRIGGER ALL;
ALTER TABLE public.packages DISABLE TRIGGER ALL;
ALTER TABLE public.check_ins DISABLE TRIGGER ALL;
ALTER TABLE public.checklists DISABLE TRIGGER ALL;
ALTER TABLE public.clinical_images DISABLE TRIGGER ALL;
ALTER TABLE public.consent_forms DISABLE TRIGGER ALL;
ALTER TABLE public.customer_special_notes DISABLE TRIGGER ALL;
ALTER TABLE public.customer_treatment_memos DISABLE TRIGGER ALL;
ALTER TABLE public.form_submissions DISABLE TRIGGER ALL;
ALTER TABLE public.health_q_results DISABLE TRIGGER ALL;
ALTER TABLE public.health_q_tokens DISABLE TRIGGER ALL;
ALTER TABLE public.insurance_claims DISABLE TRIGGER ALL;
ALTER TABLE public.insurance_documents DISABLE TRIGGER ALL;
ALTER TABLE public.insurance_receipts DISABLE TRIGGER ALL;
ALTER TABLE public.medical_charts DISABLE TRIGGER ALL;
ALTER TABLE public.message_logs DISABLE TRIGGER ALL;
ALTER TABLE public.notification_opt_outs DISABLE TRIGGER ALL;
ALTER TABLE public.package_payments DISABLE TRIGGER ALL;
ALTER TABLE public.package_sessions DISABLE TRIGGER ALL;
ALTER TABLE public.payment_code_claims DISABLE TRIGGER ALL;
ALTER TABLE public.payments DISABLE TRIGGER ALL;
ALTER TABLE public.prescriptions DISABLE TRIGGER ALL;
ALTER TABLE public.reservation_memo_history DISABLE TRIGGER ALL;
ALTER TABLE public.reservations DISABLE TRIGGER ALL;
ALTER TABLE public.service_charges DISABLE TRIGGER ALL;
INSERT INTO public.customers SELECT * FROM cleanup_bak_20260628110546.customers ON CONFLICT DO NOTHING;
INSERT INTO public.packages SELECT * FROM cleanup_bak_20260628110546.packages ON CONFLICT DO NOTHING;
INSERT INTO public.check_ins SELECT * FROM cleanup_bak_20260628110546.check_ins ON CONFLICT DO NOTHING;
INSERT INTO public.checklists SELECT * FROM cleanup_bak_20260628110546.checklists ON CONFLICT DO NOTHING;
INSERT INTO public.clinical_images SELECT * FROM cleanup_bak_20260628110546.clinical_images ON CONFLICT DO NOTHING;
INSERT INTO public.consent_forms SELECT * FROM cleanup_bak_20260628110546.consent_forms ON CONFLICT DO NOTHING;
INSERT INTO public.customer_special_notes SELECT * FROM cleanup_bak_20260628110546.customer_special_notes ON CONFLICT DO NOTHING;
INSERT INTO public.customer_treatment_memos SELECT * FROM cleanup_bak_20260628110546.customer_treatment_memos ON CONFLICT DO NOTHING;
INSERT INTO public.form_submissions SELECT * FROM cleanup_bak_20260628110546.form_submissions ON CONFLICT DO NOTHING;
INSERT INTO public.health_q_results SELECT * FROM cleanup_bak_20260628110546.health_q_results ON CONFLICT DO NOTHING;
INSERT INTO public.health_q_tokens SELECT * FROM cleanup_bak_20260628110546.health_q_tokens ON CONFLICT DO NOTHING;
INSERT INTO public.insurance_claims SELECT * FROM cleanup_bak_20260628110546.insurance_claims ON CONFLICT DO NOTHING;
INSERT INTO public.insurance_documents SELECT * FROM cleanup_bak_20260628110546.insurance_documents ON CONFLICT DO NOTHING;
INSERT INTO public.insurance_receipts SELECT * FROM cleanup_bak_20260628110546.insurance_receipts ON CONFLICT DO NOTHING;
INSERT INTO public.medical_charts SELECT * FROM cleanup_bak_20260628110546.medical_charts ON CONFLICT DO NOTHING;
INSERT INTO public.message_logs SELECT * FROM cleanup_bak_20260628110546.message_logs ON CONFLICT DO NOTHING;
INSERT INTO public.notification_opt_outs SELECT * FROM cleanup_bak_20260628110546.notification_opt_outs ON CONFLICT DO NOTHING;
INSERT INTO public.package_payments SELECT * FROM cleanup_bak_20260628110546.package_payments ON CONFLICT DO NOTHING;
INSERT INTO public.package_sessions SELECT * FROM cleanup_bak_20260628110546.package_sessions ON CONFLICT DO NOTHING;
INSERT INTO public.payment_code_claims SELECT * FROM cleanup_bak_20260628110546.payment_code_claims ON CONFLICT DO NOTHING;
INSERT INTO public.payments SELECT * FROM cleanup_bak_20260628110546.payments ON CONFLICT DO NOTHING;
INSERT INTO public.prescriptions SELECT * FROM cleanup_bak_20260628110546.prescriptions ON CONFLICT DO NOTHING;
INSERT INTO public.reservation_memo_history SELECT * FROM cleanup_bak_20260628110546.reservation_memo_history ON CONFLICT DO NOTHING;
INSERT INTO public.reservations SELECT * FROM cleanup_bak_20260628110546.reservations ON CONFLICT DO NOTHING;
INSERT INTO public.service_charges SELECT * FROM cleanup_bak_20260628110546.service_charges ON CONFLICT DO NOTHING;
ALTER TABLE public.customers ENABLE TRIGGER ALL;
ALTER TABLE public.packages ENABLE TRIGGER ALL;
ALTER TABLE public.check_ins ENABLE TRIGGER ALL;
ALTER TABLE public.checklists ENABLE TRIGGER ALL;
ALTER TABLE public.clinical_images ENABLE TRIGGER ALL;
ALTER TABLE public.consent_forms ENABLE TRIGGER ALL;
ALTER TABLE public.customer_special_notes ENABLE TRIGGER ALL;
ALTER TABLE public.customer_treatment_memos ENABLE TRIGGER ALL;
ALTER TABLE public.form_submissions ENABLE TRIGGER ALL;
ALTER TABLE public.health_q_results ENABLE TRIGGER ALL;
ALTER TABLE public.health_q_tokens ENABLE TRIGGER ALL;
ALTER TABLE public.insurance_claims ENABLE TRIGGER ALL;
ALTER TABLE public.insurance_documents ENABLE TRIGGER ALL;
ALTER TABLE public.insurance_receipts ENABLE TRIGGER ALL;
ALTER TABLE public.medical_charts ENABLE TRIGGER ALL;
ALTER TABLE public.message_logs ENABLE TRIGGER ALL;
ALTER TABLE public.notification_opt_outs ENABLE TRIGGER ALL;
ALTER TABLE public.package_payments ENABLE TRIGGER ALL;
ALTER TABLE public.package_sessions ENABLE TRIGGER ALL;
ALTER TABLE public.payment_code_claims ENABLE TRIGGER ALL;
ALTER TABLE public.payments ENABLE TRIGGER ALL;
ALTER TABLE public.prescriptions ENABLE TRIGGER ALL;
ALTER TABLE public.reservation_memo_history ENABLE TRIGGER ALL;
ALTER TABLE public.reservations ENABLE TRIGGER ALL;
ALTER TABLE public.service_charges ENABLE TRIGGER ALL;
COMMIT;
-- 복원 검증: SELECT count(*) FROM public.customers WHERE id IN (SELECT id FROM cleanup_bak_20260628110546.customers);
