-- ============================================================================
-- T-20260603-foot-CUSTNAME-CASCADE-DASH — AC-4 백필(backfill) SQL
-- ⚠️ supervisor 게이트 + planner 승인 게이트. dev-foot 자동 실행하지 않음.
--
-- 목적:
--   go-forward 수정(Customers.tsx save() 카스케이드) 이전에 이미 발생한
--   reservations.customer_name / check_ins.customer_name ↔ customers.name 불일치 정정.
--
-- DRY-RUN 결과 (2026-06-03, service_role 경유 read-only):
--   divergent reservations: 14건
--   divergent check_ins   : 12건  (합계 26건)
--   대상 데이터는 전부 테스트/더미(테스트환자·더미_초진·김N번·고양이/까꿍 등). 실환자 PII 아님.
--
-- ⚠️⚠️ 중대 주의 — 백필을 일괄 실행하면 안 됨 ⚠️⚠️
--   불일치 26건은 두 종류가 섞여 있다:
--     (a) 정상 개명 후 카스케이드 누락 → customer_name 을 customers.name 으로 갱신해야 맞음.
--     (b) phone-dedup(placeholder 0000) 오연결 → customer_id 가 '다른 사람'을 가리킴.
--         예) resv 453aacb3 "인도네시아 메가인플루언서" → "빈혜린(원내촬영)"
--             = T-20260603-foot-DASH-SLOT-CHART-MISMAP 가 다룬 바로 그 오연결.
--         이 경우 customer_name 을 customers.name 으로 덮으면 '예약 본래 이름'을 파괴하고
--         오연결을 은폐(RES-NAME-MISMATCH-WARN 경고가 잡아야 할 신호 소실)한다.
--   (a)와 (b)는 자동 구분 불가 → 반드시 행 단위 검토 후 (a)만 선별 적용할 것.
--
-- 권고:
--   - go-forward 수정만으로 신규 개명은 전부 정상 카스케이드 → 신규 불일치 발생 없음.
--   - 과거 26건은 전부 테스트 데이터 + 대부분 cancelled/noshow/done → 라이브 노출 위험 낮음.
--   - 백필 강행보다, 오연결분(b)은 DASH-SLOT-CHART-MISMAP datafix 와 동일 패턴으로
--     customer_id 정정이 맞고, 순수 개명분(a)만 customer_name 갱신 권장.
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────
-- (0) DRY-RUN: 불일치 행 전수 조회 (적용 전 반드시 실행해 (a)/(b) 분류)
-- ─────────────────────────────────────────────────────────────────────────
-- SELECT r.id, r.customer_id, r.customer_name AS denorm, c.name AS real_name, r.status
--   FROM reservations r JOIN customers c ON c.id = r.customer_id
--  WHERE r.customer_id IS NOT NULL
--    AND COALESCE(TRIM(r.customer_name),'') <> COALESCE(TRIM(c.name),'')
--  ORDER BY r.status, r.id;
--
-- SELECT k.id, k.customer_id, k.customer_name AS denorm, c.name AS real_name, k.status
--   FROM check_ins k JOIN customers c ON c.id = k.customer_id
--  WHERE k.customer_id IS NOT NULL
--    AND COALESCE(TRIM(k.customer_name),'') <> COALESCE(TRIM(c.name),'')
--  ORDER BY k.status, k.id;

-- ─────────────────────────────────────────────────────────────────────────
-- (1) 선별 백필 — (a) 순수 개명분만. 검토 후 대상 id 를 명시해 적용.
--     ※ 절대 WHERE 절 없이 전 divergent 행을 일괄 UPDATE 하지 말 것((b) 오염).
-- ─────────────────────────────────────────────────────────────────────────
-- BEGIN;
-- UPDATE reservations r
--    SET customer_name = c.name
--   FROM customers c
--  WHERE c.id = r.customer_id
--    AND r.id IN ( /* 검토 후 확정된 (a) 개명 예약 id 들 */ );
--
-- UPDATE check_ins k
--    SET customer_name = c.name
--   FROM customers c
--  WHERE c.id = k.customer_id
--    AND k.id IN ( /* 검토 후 확정된 (a) 개명 체크인 id 들 */ );
-- COMMIT;

-- ─────────────────────────────────────────────────────────────────────────
-- ROLLBACK 메모: 백필 전 (0) 조회 결과(denorm 원본값)를 보관해야 원복 가능.
--   행 단위 UPDATE ... SET customer_name = '<원본 denorm>' WHERE id = '...';
-- ─────────────────────────────────────────────────────────────────────────
