-- T-20260710-foot-SECDEF-ANON-REVOKE  ★ SUPERSEDED / INERT NO-OP (2026-07-18) ★
-- ══════════════════════════════════════════════════════════════════════════════
-- 이 마이그레이션은 CLOSE-AS-SUPERSEDED 되었다. 절대 apply 하지 말 것.
-- (파일은 이력 보존 + tooling 이 실수로 실행해도 무해하도록 inert no-op 로 대체.)
-- ══════════════════════════════════════════════════════════════════════════════
--
-- 사유 (supervisor DB-GATE NO-GO 2026-07-18 + dev-foot 재baseline):
--   원안(anon 119→14 whitelist)은 2026-07-10 baseline 기준으로 작성됐으나,
--   현 prod(rxlomoozakkjesdqjtvd, 2026-07-18 실측)는 anon=33 으로 drift.
--   핵심 보안목표는 더 넓고 최신인 별도 sweep 으로 **이미 달성**됨:
--     · postgres 창조경로 pg_default_acl 에서 PUBLIC·anon 이미 제거 (= 원안 step1).
--     · Tier-A 돈-함수 anon EXECUTE = FALSE (transfer_package_atomic 등, money-func anon-grant 0건).
--     · anon-EXECUTE 119 → 33 (전량 self-checkin/health-q/reservation intake self-service CLASS).
--   원안을 지금 apply 하면 **회귀**: whitelist 14 에 없는 live self-service 함수 회수 →
--     self_checkin_lookup(anon 34회/89d)·get_today_reservations(anon 5회) = 42501 셀프체크인 파손.
--     + is_approved_user()/current_user_is_admin_or_manager() 를 anon 에 역방향 부여(현 prod 미부여).
--
-- 증거(재baseline v2): db-gate/T-20260710-foot-SECDEF-ANON-REVOKE_dbgate_FINAL.md
-- 재현: scripts/T-20260710-foot-SECDEF-ANON-REVOKE_rebaseline_probe.mjs
--       scripts/T-20260710-foot-SECDEF-ANON-REVOKE_usage_analysis.mjs
--
-- 유일 잔여 유효 항목(본 postgres 마이그 범위 밖 → supervisor 상위권한 집행):
--   ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
--     REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon;   -- supabase_admin 경로 anon=X 잔존
--
-- 원안 SQL 전문은 git 이력(commit 50286e48 이전 버전)에 보존. 필요 시 그곳 참조.

SELECT 'T-20260710-foot-SECDEF-ANON-REVOKE superseded (no-op) — see dbgate_FINAL v2' AS note;
