-- no-persistence dry-run harness (RUN A: forward) — GENERATED by T-20260821-foot-PROGANALYSIS-BATCH-EXTRACT-LINK-DIRECTIVE_dryrun.mjs
-- strip 된 top-level txn 제어문(INV-5 비침묵): ["BEGIN;","COMMIT;"]
-- sentinel RAISE 로 subtransaction 강제 롤백 → prod 영속 0. 아래는 실제 전송된 harness SQL.
DO $dr_harness0$
BEGIN
  EXECUTE $dr_body0$
-- ============================================================
-- T-20260821-foot-PROGANALYSIS-BATCH-EXTRACT-LINK-DIRECTIVE (Phase-2 §4/§5) — 경과분석 배치 슬립 상태머신 스키마
-- ============================================================
-- DA CONSULT-REPLY(정본): GO(조건부, ADDITIVE) — DA-20260822-foot-PROGANALYSIS-SLIP-SCHEMA (MSG-20260822-004858-nlnt)
--   정본 decision: agents/docs/da_replies/da_decision_foot_proganalysis_slip_schema_extract_link_20260822.md
--
-- ⚠️ AC-0(불변): DA GO ≠ apply 허가. 신규 테이블/컬럼/RLS/트리거 = DDL → apply-gate=supervisor.
--    이 파일은 dev-foot 가 작성한 DRAFT. prod apply 는 supervisor DDL-diff + 롤백SQL + 물리 GO-token 발행 後에만.
--    'ADDITIVE' ≠ apply-gate 면제(대표게이트만 면제 §3.1). GO-token 前 prod 선집행 금지.
--
-- change-class = ADDITIVE (신규 테이블 2 · 컬럼 다수 · CHECK · RESTRICTIVE · BEFORE DELETE 가드 · audit 트리거).
--   DROP/타입변경/소급변형 0. 대표게이트 면제(§3.1). supervisor DDL-diff + 롤백 SQL + GO-token 後 apply.
-- 멱등: idempotent (IF NOT EXISTS / DROP POLICY IF EXISTS / CREATE OR REPLACE).
-- 롤백: 20260822010000_foot_progress_analysis_slips_schema.rollback.sql
--
-- ── DA 판정 매핑 ──────────────────────────────────────────────────────
--   [Q2-1] 스키마 배치 = 후보 B(전용 slip 테이블 신설). 후보 A(progress_result_images 확장) REJECT.
--          근거=grain 충돌(slip 1:1 예약 vs 이미지 1:N 방문). placeholder 행이 부모 content_hash automatch 계약 오염 → 금지.
--          → 신규 progress_analysis_slips(1행=경과지1장=예약1건, durable) + progress_analysis_slips_audit_log(Q2-3)
--          + 기존 progress_result_images additive(slip_id FK + soft-delete). slip:images = 1:N.
--          부모 계약(chart_no 단독조인 G1 · 이름 대조가드 G2 · content_hash 멱등 · 오매칭 6가드) 전부 불변.
--   [Q2-1] state = text + CHECK IN('pending_extract','awaiting_upload','confirmed'). native enum 금지.
--          저장 = 슬러그 canonical(한글 표시명은 FE 매핑 — NFD 재발 회피). UNIQUE(reservation_id).
--   [Q2-2] 예약 1:1 결속키 = slips.reservation_id UNIQUE(plain, slip=soft-delete 없음).
--          resolve 술어(fail-closed)는 FE/RPC 배선 단계 코드-핀. under-bind ≫ mis-bind. fuzzy 금지.
--          session_ordinal ↔ progressSixMultiple(anticipated%6==0) 결정적 매핑 = 배선단계 코드-핀(본 스키마는 int 컬럼만).
--   [Q2-3] ★soft-delete 위치 = progress_result_images(이미지=삭제/복구 대상 PHI), slip 아님.
--          노쇼/취소 = 이미지 soft-delete + slip.state 를 pending_extract 로 revert(≠delete). slip 은 durable.
--          컬럼셋(form_submissions 선례 미러) + hard-DELETE 전면차단(BEFORE DELETE 가드 RAISE).
--          감사 = 신규 slips_audit_log(form_submissions_audit_log 미러): append-only · INSERT=SECDEF트리거 · SELECT=director/admin.
--   [Q2-5] RLS(foot canonical §A-3): slips=RESTRICTIVE clinic-gate (clinic_id=current_user_clinic_id() OR is_admin_or_manager()).
--          images 삭제행 SELECT = (deleted_at IS NULL OR is_admin_or_manager()) (FE 훅 .eq is_deleted=false belt).
--          audit_log SELECT=director/admin · INSERT=SECDEF. clinic_id NOT NULL(NULL silent lockout 금지).
--
-- ── ★divergence 해소(dev-foot flag → planner FOLLOWUP 동반) ─────────────
--   DA reply 축약본은 "is_deleted bool NOT NULL DEFAULT false" 를 적었으나, 같은 판정이 명한 "form_submissions 선례 미러"
--   의 실제 canonical(20260802150000, DA 자기정정본)은 mutable is_deleted BOOL 을 REJECT 하고 authority=deleted_at 단일 atom
--   + is_deleted GENERATED(deleted_at IS NOT NULL) STORED 로 확정했다(A9 잠복불변식 위반 클래스 회피).
--   PHI 테이블에 mutable is_deleted 재도입 = DA 가 form_submissions 에서 명시적으로 금지한 클래스 신규주조.
--   → 명시된 '선례 미러' 를 우선(deleted_at authority + is_deleted GENERATED)하여 초안 작성.
--   이 divergence 는 planner FOLLOWUP 으로 DA 확인 요청(GO-token/apply 前 confirm). 축약본 문구를 문자 그대로 채택 시
--   재작성(1컬럼 형태 전환)만 필요 — 나머지 스키마 불변.
--
-- ── §6 노쇼 자동폐기(Q2-4) 는 본 마이그 범위 밖 ──────────────────────────
--   스키마(soft-delete·휴지통·감사)=본 GO. 자동폐기 '트리거 실배선' = 스키마 GO ∧ reporter confirm(hxdj) 後 별도 마이그.
--   삭제 술어(불변·fail-closed·reservation_id ONLY): images WHERE slip_id=(slips.reservation_id=취소/노쇼 예약ID)
--     AND slip.state<>'confirmed' AND NOT EXISTS(체크인) AND is_deleted=false. 이름·날짜 술어 금지. → §6 마이그에서 배선.
-- ============================================================



-- ── 단계 1. progress_analysis_slips (신규 · 후보 B · 1행=경과지1장=예약1건 · durable) ──────────
--   Q2-1: state=slug canonical + CHECK. Q2-2: UNIQUE(reservation_id) plain(soft-delete 없음).
CREATE TABLE IF NOT EXISTS public.progress_analysis_slips (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id      uuid        NOT NULL REFERENCES public.clinics(id),          -- Q2-5: NOT NULL(NULL silent lockout 금지)
  customer_id    uuid        NOT NULL REFERENCES public.customers(id),        -- durable: NO ACTION(고객 병합/삭제 시 slip 보존 우선)
  reservation_id uuid        NOT NULL REFERENCES public.reservations(id),     -- Q2-2 1:1 결속키
  chart_no       text        NOT NULL,                                        -- 파일명 파싱/조인 축(부모 G1 계약과 정합)
  session_ordinal integer    NOT NULL,                                        -- 6배수 마일스톤 회차(anticipated%6==0 → progressSixMultiple, 배선단계 결정적 매핑)
  visit_date     date        NOT NULL,                                        -- 방문일(6배수 도래일)
  state          text        NOT NULL DEFAULT 'pending_extract'
                             CHECK (state IN ('pending_extract','awaiting_upload','confirmed')),  -- Q2-1 slug canonical(한글=FE 매핑)
  created_by     uuid        REFERENCES auth.users(id),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  -- Q2-2: 예약 1:1 결속 — under-bind ≫ mis-bind. 후보 2건↑/date 불일치 시 결속 금지(FE fail-closed).
  CONSTRAINT progress_analysis_slips_reservation_uq UNIQUE (reservation_id)
);

CREATE INDEX IF NOT EXISTS idx_pas_clinic_state ON public.progress_analysis_slips(clinic_id, state, visit_date DESC);
CREATE INDEX IF NOT EXISTS idx_pas_customer     ON public.progress_analysis_slips(customer_id, visit_date DESC);
CREATE INDEX IF NOT EXISTS idx_pas_chart        ON public.progress_analysis_slips(clinic_id, chart_no, visit_date);

COMMENT ON TABLE public.progress_analysis_slips IS
  '경과분석 배치 슬립 상태머신(추출대상 pending_extract → 업로드대기 awaiting_upload → 확정 confirmed). 1행=경과지1장=예약1건(durable). state=slug canonical(한글=FE). UNIQUE(reservation_id). 후보 B(전용테이블). DA-20260822-foot-PROGANALYSIS-SLIP-SCHEMA.';
COMMENT ON COLUMN public.progress_analysis_slips.state IS
  'slug canonical: pending_extract(추출대상)/awaiting_upload(업로드대기)/confirmed(확정). 노쇼/취소 시 pending_extract 로 revert(≠delete, slip durable). native enum 금지.';
COMMENT ON COLUMN public.progress_analysis_slips.session_ordinal IS
  '6배수 마일스톤 회차. anticipated%6==0(progressSixMultiple) 결정적 매핑(FE/RPC 배선 코드-핀). fuzzy 금지.';

ALTER TABLE public.progress_analysis_slips ENABLE ROW LEVEL SECURITY;

-- Q2-5 permissive CRUD(clinic 스코프 + is_admin_or_manager=admin/manager/director) — PHI-인접 임상 배치레코드 tier.
DROP POLICY IF EXISTS "pas_select" ON public.progress_analysis_slips;
CREATE POLICY "pas_select" ON public.progress_analysis_slips
  FOR SELECT TO authenticated
  USING (clinic_id = public.current_user_clinic_id() AND public.is_admin_or_manager());

DROP POLICY IF EXISTS "pas_insert" ON public.progress_analysis_slips;
CREATE POLICY "pas_insert" ON public.progress_analysis_slips
  FOR INSERT TO authenticated
  WITH CHECK (clinic_id = public.current_user_clinic_id() AND public.is_admin_or_manager());

DROP POLICY IF EXISTS "pas_update" ON public.progress_analysis_slips;
CREATE POLICY "pas_update" ON public.progress_analysis_slips
  FOR UPDATE TO authenticated
  USING (clinic_id = public.current_user_clinic_id() AND public.is_admin_or_manager())
  WITH CHECK (clinic_id = public.current_user_clinic_id() AND public.is_admin_or_manager());

-- Q2-5 RESTRICTIVE clinic-gate (foot canonical §A-3) — 기존 permissive 와 AND. admin bypass=is_admin_or_manager.
DROP POLICY IF EXISTS "pas_clinic_gate" ON public.progress_analysis_slips;
CREATE POLICY "pas_clinic_gate" ON public.progress_analysis_slips
  AS RESTRICTIVE
  FOR ALL TO authenticated
  USING (clinic_id = public.current_user_clinic_id() OR public.is_admin_or_manager());

-- ── 단계 2. progress_analysis_slips_audit_log (신규 · form_submissions_audit_log 미러 · append-only) ──
--   Q2-3: state 전이 감사. INSERT=SECDEF 트리거 · SELECT=director/admin · UPDATE/DELETE 정책 부재(위변조 불가).
CREATE TABLE IF NOT EXISTS public.progress_analysis_slips_audit_log (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  slip_id     uuid        NOT NULL REFERENCES public.progress_analysis_slips(id) ON DELETE RESTRICT,  -- forensics-correct backstop
  clinic_id   uuid,                                                       -- Q2-5 uuid 타입정합
  operation   text        NOT NULL CHECK (operation IN ('INSERT','UPDATE','DELETE')),
  old_data    jsonb,                                                      -- 전이 전 행(INSERT 시 NULL)
  new_data    jsonb,                                                      -- 전이 후 행(DELETE 시 NULL)
  actor       uuid,                                                       -- 수행자 auth.uid()
  ts          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pasal_slip   ON public.progress_analysis_slips_audit_log(slip_id, ts DESC);
CREATE INDEX IF NOT EXISTS idx_pasal_clinic ON public.progress_analysis_slips_audit_log(clinic_id, ts DESC);

COMMENT ON TABLE public.progress_analysis_slips_audit_log IS
  '경과분석 슬립 상태전이 Audit Trail(append-only). INSERT=SECDEF 트리거 · SELECT=director/admin · UPDATE/DELETE 불가. form_submissions_audit_log 미러. DA-20260822-foot-PROGANALYSIS-SLIP-SCHEMA.';

ALTER TABLE public.progress_analysis_slips_audit_log ENABLE ROW LEVEL SECURITY;

-- SELECT: director/admin 만(old/new_data=full-row 임상메타).
DROP POLICY IF EXISTS "pasal_select_director_admin" ON public.progress_analysis_slips_audit_log;
CREATE POLICY "pasal_select_director_admin" ON public.progress_analysis_slips_audit_log
  FOR SELECT TO authenticated
  USING (current_user_role() = ANY (ARRAY['director'::text, 'admin'::text]));

-- INSERT: 정상 경로 = SECDEF 트리거(RLS bypass). 직접 INSERT belt = 승인 사용자만.
DROP POLICY IF EXISTS "pasal_insert_approved" ON public.progress_analysis_slips_audit_log;
CREATE POLICY "pasal_insert_approved" ON public.progress_analysis_slips_audit_log
  FOR INSERT TO authenticated
  WITH CHECK (is_approved_user());
-- UPDATE/DELETE 정책 없음 → append-only 강제(위변조 불가).

-- 슬립 상태전이 감사 트리거(SECURITY DEFINER, form_submissions_body_audit 미러).
CREATE OR REPLACE FUNCTION public.progress_analysis_slips_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.progress_analysis_slips_audit_log (slip_id, clinic_id, operation, old_data, new_data, actor)
    VALUES (NEW.id, NEW.clinic_id, 'INSERT', NULL, row_to_json(NEW)::jsonb, auth.uid());
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO public.progress_analysis_slips_audit_log (slip_id, clinic_id, operation, old_data, new_data, actor)
    VALUES (OLD.id, OLD.clinic_id, 'UPDATE', row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb, auth.uid());
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO public.progress_analysis_slips_audit_log (slip_id, clinic_id, operation, old_data, new_data, actor)
    VALUES (OLD.id, OLD.clinic_id, 'DELETE', row_to_json(OLD)::jsonb, NULL, auth.uid());
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$;

COMMENT ON FUNCTION public.progress_analysis_slips_audit() IS
  '경과분석 슬립 상태전이 감사(append-only, SECDEF). INSERT/UPDATE/DELETE 전·후 스냅샷 보존. DA-20260822-foot-PROGANALYSIS-SLIP-SCHEMA.';

DROP TRIGGER IF EXISTS trg_progress_analysis_slips_audit ON public.progress_analysis_slips;
CREATE TRIGGER trg_progress_analysis_slips_audit
  AFTER INSERT OR UPDATE OR DELETE ON public.progress_analysis_slips
  FOR EACH ROW EXECUTE FUNCTION public.progress_analysis_slips_audit();

-- updated_at 자동갱신.
CREATE OR REPLACE FUNCTION public.progress_analysis_slips_touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS trg_progress_analysis_slips_touch ON public.progress_analysis_slips;
CREATE TRIGGER trg_progress_analysis_slips_touch
  BEFORE UPDATE ON public.progress_analysis_slips
  FOR EACH ROW EXECUTE FUNCTION public.progress_analysis_slips_touch_updated_at();

-- ── 단계 3. progress_result_images ADDITIVE — slip_id FK(1:N) + soft-delete(Q2-3) ──────────
--   ★soft-delete 위치 = 이미지(삭제/복구 대상 PHI). authority=deleted_at 단일 atom + is_deleted GENERATED(form_submissions 선례).
ALTER TABLE public.progress_result_images
  ADD COLUMN IF NOT EXISTS slip_id       uuid        NULL REFERENCES public.progress_analysis_slips(id) ON DELETE SET NULL,  -- slip:images=1:N, slip 삭제 대비 SET NULL(이미지 durable)
  ADD COLUMN IF NOT EXISTS deleted_at    timestamptz NULL,   -- soft-delete 단일 authority(NULL=활성)
  ADD COLUMN IF NOT EXISTS deleted_by    uuid        NULL,   -- 삭제 수행자 auth.uid()
  ADD COLUMN IF NOT EXISTS delete_reason text        NULL,   -- 삭제 사유(노쇼/취소/오첨부 등)
  ADD COLUMN IF NOT EXISTS is_deleted    boolean     GENERATED ALWAYS AS (deleted_at IS NOT NULL) STORED;  -- FE parity belt(파생, drift 구조불가)

COMMENT ON COLUMN public.progress_result_images.slip_id IS 'FK→progress_analysis_slips(id). slip:images=1:N. slip 삭제 시 SET NULL(이미지 durable). DA-20260822.';
COMMENT ON COLUMN public.progress_result_images.deleted_at IS 'soft-delete 단일 authority(NULL=활성). 노쇼/취소=soft-delete(+slip.state pending_extract revert). hard-DELETE 금지(BEFORE DELETE 가드). PHI 의료법 §40 10년(물리 잔존). DA-20260822.';
COMMENT ON COLUMN public.progress_result_images.is_deleted IS 'GENERATED(deleted_at IS NOT NULL) — FE parity belt 전용 파생. write 불가(soft-delete=deleted_at 설정으로만). authority=deleted_at. DA-20260822.';

-- 멱등/복구: 부모 onConflict(clinic_id,chart_no,visit_date,content_hash) 유지 → 동일content 재업로드 = soft-deleted 행 revive(신규행 금지).
--   활성행 목록 최적화 partial index(술어 통일 = deleted_at IS NULL).
CREATE INDEX IF NOT EXISTS idx_pri_active
  ON public.progress_result_images (clinic_id, visit_date DESC)
  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_pri_slip ON public.progress_result_images(slip_id);

-- soft-delete = UPDATE(deleted_at). 기존 progress_result_images 에 UPDATE 정책 부재 → 추가(ADDITIVE).
DROP POLICY IF EXISTS "pri_admin_update" ON public.progress_result_images;
CREATE POLICY "pri_admin_update" ON public.progress_result_images
  FOR UPDATE TO authenticated
  USING (clinic_id = public.current_user_clinic_id() AND public.is_admin_or_manager())
  WITH CHECK (clinic_id = public.current_user_clinic_id() AND public.is_admin_or_manager());

-- Q2-3: hard-DELETE 전면차단(BEFORE DELETE 가드 RAISE). 모든 삭제는 soft-delete(UPDATE deleted_at)로만.
--   정당 purge=service_role 의 의도적 ALTER TABLE ... DISABLE TRIGGER 경유(form_submissions 선례). 기존 pri_own_delete 정책은
--   본 가드에 의해 무효화(무손실·ADDITIVE, 정책 DROP 안 함 — DA DROP 0 준수).
CREATE OR REPLACE FUNCTION public.progress_result_images_harddelete_guard()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '경과분석 결과이미지는 물리적으로 삭제할 수 없습니다 — 삭제는 무효화(soft-delete) 기록으로만 가능합니다'
    USING ERRCODE = '42501';
  RETURN NULL;
END;
$$;
COMMENT ON FUNCTION public.progress_result_images_harddelete_guard() IS
  'progress_result_images hard-DELETE 전면차단(PHI 의료법 §40). 모든 삭제=soft-delete(deleted_at). 정당 purge=service_role DISABLE TRIGGER. DA-20260822.';
DROP TRIGGER IF EXISTS trg_progress_result_images_harddelete_guard ON public.progress_result_images;
CREATE TRIGGER trg_progress_result_images_harddelete_guard
  BEFORE DELETE ON public.progress_result_images
  FOR EACH ROW EXECUTE FUNCTION public.progress_result_images_harddelete_guard();

-- Q2-3 휴지통 7일 = 조회필터(display window), 물리이동 아님(행·blob 물리잔존). 자동 하드퍼지 = 본 티켓 HARD-BLOCK(CEO/legal 별건).
-- Q2-5 images 삭제행 SELECT = (deleted_at IS NULL OR is_admin_or_manager()) RESTRICTIVE(기존 pri_admin_select 와 AND).
DROP POLICY IF EXISTS "pri_deleted_rows_admin_only" ON public.progress_result_images;
CREATE POLICY "pri_deleted_rows_admin_only" ON public.progress_result_images
  AS RESTRICTIVE
  FOR SELECT TO authenticated
  USING (deleted_at IS NULL OR public.is_admin_or_manager());

COMMENT ON POLICY "pri_deleted_rows_admin_only" ON public.progress_result_images IS
  'soft-delete 결과이미지(deleted_at IS NOT NULL)는 is_admin_or_manager(admin/manager/director) 만 조회. 술어=deleted_at 단일 authority. RESTRICTIVE. DA-20260822.';

-- ── 검증(마이그 자체 유효성, supervisor DDL-diff self-check) ──────────────
DO $$
BEGIN
  -- Q2-1: slips 테이블 + state CHECK + reservation UNIQUE
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='progress_analysis_slips') THEN
    RAISE EXCEPTION 'progress_analysis_slips 생성 실패'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='progress_analysis_slips_reservation_uq') THEN
    RAISE EXCEPTION 'Q2-2 위반: UNIQUE(reservation_id) 누락'; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='progress_analysis_slips'
      AND column_name='state' AND data_type='text') THEN
    RAISE EXCEPTION 'Q2-1 위반: state text 컬럼 누락(native enum 금지)'; END IF;
  -- Q2-1: state CHECK 3-slug 존재
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.progress_analysis_slips'::regclass AND contype='c'
      AND pg_get_constraintdef(oid) ILIKE '%pending_extract%awaiting_upload%confirmed%') THEN
    RAISE EXCEPTION 'Q2-1 위반: state CHECK 3-slug 누락'; END IF;
  -- Q2-5: slips RESTRICTIVE clinic-gate
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='progress_analysis_slips'
      AND policyname='pas_clinic_gate' AND permissive='RESTRICTIVE') THEN
    RAISE EXCEPTION 'Q2-5 위반: slips RESTRICTIVE clinic-gate 누락'; END IF;
  -- Q2-3: audit_log 테이블 + append-only(UPDATE/DELETE 정책 부재) + director/admin SELECT
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='progress_analysis_slips_audit_log') THEN
    RAISE EXCEPTION 'Q2-3 위반: slips_audit_log 생성 실패'; END IF;
  IF EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='progress_analysis_slips_audit_log' AND cmd IN ('UPDATE','DELETE')) THEN
    RAISE EXCEPTION 'Q2-3 위반: audit_log 에 UPDATE/DELETE 정책 존재 — append-only 위반'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='progress_analysis_slips_audit_log'
      AND policyname='pasal_select_director_admin' AND qual ILIKE '%director%') THEN
    RAISE EXCEPTION 'Q2-3 위반: audit_log SELECT director/admin 술어 누락'; END IF;
  -- Q2-3: 감사 트리거 존재
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_progress_analysis_slips_audit' AND tgrelid='public.progress_analysis_slips'::regclass) THEN
    RAISE EXCEPTION 'Q2-3 위반: slips 감사 트리거 누락'; END IF;
  -- Q2-3: images soft-delete 컬럼(deleted_at authority + is_deleted GENERATED) + slip_id FK
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='progress_result_images' AND column_name='deleted_at') THEN
    RAISE EXCEPTION 'Q2-3 위반: images.deleted_at 누락'; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='progress_result_images'
      AND column_name='is_deleted' AND is_generated='ALWAYS') THEN
    RAISE EXCEPTION '★divergence 해소 위반: images.is_deleted 가 GENERATED 아님(선례 미러 — mutable bool 금지)'; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='progress_result_images' AND column_name='slip_id') THEN
    RAISE EXCEPTION 'Q2-1 위반: images.slip_id FK 누락'; END IF;
  -- Q2-3: hard-DELETE 가드 트리거
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_progress_result_images_harddelete_guard' AND tgrelid='public.progress_result_images'::regclass) THEN
    RAISE EXCEPTION 'Q2-3 위반: images hard-DELETE 가드 트리거 누락'; END IF;
  -- Q2-5: images 삭제행 RESTRICTIVE
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='progress_result_images'
      AND policyname='pri_deleted_rows_admin_only' AND permissive='RESTRICTIVE') THEN
    RAISE EXCEPTION 'Q2-5 위반: images 삭제행 RESTRICTIVE 누락'; END IF;

  RAISE NOTICE 'T-20260821-foot-PROGANALYSIS-BATCH-EXTRACT-LINK-DIRECTIVE Phase-2 §4/§5(DA-20260822-SLIP-SCHEMA): 검증 통과 (slips 후보B + reservation UNIQUE + state slug CHECK + RESTRICTIVE clinic-gate + audit append-only director/admin + images soft-delete deleted_at authority/GENERATED + slip_id 1:N + hard-DELETE 가드)';
END $$;
DO $dr_sentinel0$ BEGIN RAISE EXCEPTION 'DRYRUN_OK_ABORT: all checks passed, forced rollback'; END $dr_sentinel0$;

  $dr_body0$;
EXCEPTION WHEN OTHERS THEN
  IF POSITION('DRYRUN_OK_ABORT' IN COALESCE(SQLERRM, '')) > 0 THEN
    RAISE NOTICE 'DRYRUN_OK_ABORT sentinel reached — subtransaction rolled back (non-persistent)';
  ELSE
    RAISE;
  END IF;
END
$dr_harness0$;
