-- ROLLBACK T-20260629-foot-ANON-PII-LEAK Phase 1 (긴급 복구용 — 권한 재부여)
BEGIN;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.staff         TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.user_profiles TO anon;
GRANT DELETE, TRUNCATE, REFERENCES, TRIGGER         ON public.customers    TO anon;
GRANT DELETE, TRUNCATE, REFERENCES, TRIGGER         ON public.check_ins    TO anon;
GRANT INSERT, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.reservations TO anon;
COMMIT;
