// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Storage-dedicated client — CRM_long Supabase where storage RLS policies are configured.
// Lovable deployment may use a different Supabase for data; this ensures photo uploads
// always go to the project with proper storage.objects policies.
const STORAGE_SUPABASE_URL = 'https://muvcfrgmxlwtidundlre.supabase.co';
const STORAGE_SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dmNmcmdteGx3dGlkdW5kbHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0MTc5MTYsImV4cCI6MjA5MTk5MzkxNn0.xeKMJB-COY9PUoYrAlA4OZjPP3N26gZO5SVtbjPRixE';
export const storageClient = createClient(STORAGE_SUPABASE_URL, STORAGE_SUPABASE_KEY);